version: '3.8'
services:
  app:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - valkey
    env_file:
      - .env
    volumes:
      - ./builds:/builds
  workers:
    build: ./worker
    environment:
      - NUM_WORKERS=1
    depends_on:
      - valkey
    env_file:
      - .env
    volumes:
      - ./builds:/builds
      - steam_config:/root/Steam
  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    command: valkey-server --requirepass ${VALKEY_PASSWORD:-change_in_production}
    volumes:
      - valkey_data:/data
volumes:
  valkey_data:
  steam_config: